# Generated by Django 4.2.19 on 2025-03-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyreportdetail',
            name='box_date',
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='disabled_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weeklyreportdetail',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
