# Generated by Django 4.2.19 on 2025-03-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_remove_weeklyreportdetail_box_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
