# Generated by Django 4.2.19 on 2025-03-06 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_box_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.lesson'),
        ),
    ]
