# Generated by Django 4.2.19 on 2025-03-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_box_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
