# Generated by Django 4.2.19 on 2025-03-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_alter_box_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='logs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
