# Generated by Django 4.2.19 on 2025-04-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_weeklyreport_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='important_events',
            field=models.TextField(blank=True, null=True),
        ),
    ]
