# Generated by Django 4.2.19 on 2025-04-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_weeklyreport_important_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
