# Generated by Django 4.2.19 on 2025-06-09 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0009_box_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Saturday', 'شنبه'), ('Sunday', 'یکشنبه'), ('Monday', 'دوشنبه'), ('Tuesday', 'سه\u200cشنبه'), ('Wednesday', 'چهارشنبه'), ('Thursday', 'پنج\u200cشنبه'), ('Friday', 'جمعه')], max_length=10, verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع دوره')),
                ('is_active', models.BooleanField(default=True, verbose_name='دوره فعال است؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.advisor', verbose_name='مشاور')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.student', verbose_name='دانش\u200cآموز')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='comment_attachments/', verbose_name='فایل ضمیمه')),
                ('voice_note', models.FileField(blank=True, null=True, upload_to='comment_voices/', verbose_name='پیام صوتی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='plans.course')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.PositiveSmallIntegerField(verbose_name='شماره جلسه')),
                ('date', models.DateField(verbose_name='تاریخ جلسه')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تیک خورده؟')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='لینک فیلم جلسه')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='plans.course')),
            ],
            options={
                'unique_together': {('course', 'session_number')},
            },
        ),
    ]
