"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-h(ofr+ccfn9xskffkx0t4=zpza%@658o8z8^2$apxtpiyvzc6!'
DEBUG = True
ALLOWED_HOSTS = ['127.0.0.1','panelkimia.ir','www.panelkimia.ir']

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'accounts',
    'plans',
    'management',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'debug': True,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'panelkim_db',
        'USER': 'panelkim_admin',
        'PASSWORD': 'tK[KL$aYj?**',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'fa-ir'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/plan/'
LOGIN_URL = '/login/'
LOGOUT_REDIRECT_URL = '/login/'

# Dashboard report downloads intentionally use ?format=csv|xlsx|json.
# Disable DRF's legacy query-parameter renderer override so that the export
# view receives this parameter instead of returning a renderer 404.
REST_FRAMEWORK = {
    'URL_FORMAT_OVERRIDE': None,
}

TELEGRAM_BOT_TOKEN = os.environ.get(
    'TELEGRAM_BOT_TOKEN',
    '8489390924:AAEx7RR147AMtZK66swBcLhEuKVowi8vfMY',
)
TELEGRAM_WORKER_URL = os.environ.get(
    'TELEGRAM_WORKER_URL',
    'https://misty-sky-f10a.hsdf7rb.workers.dev/',
)
KAVENEGAR_API_KEY = os.environ.get(
    'KAVENEGAR_API_KEY',
    '7A724E712B39625A6D4C496D375467527A554D316B31676C79757678696F674B5570684C6C52534F7063343D',
)
KAVENEGAR_SENDER = os.environ.get('KAVENEGAR_SENDER', '')
